let $numero1; // correcto caracter permitido
let _$letra; // correcto caracter permitido
//let 1numero; // incorrecto no se permite iniciar una variable con un numero
let numero;1_123; // la "let numero" es correcto, lo siguiente  es solo un numero suelto en el codigo
let $$$otroNumero; //correcto caracter permitido de inicio
let $_a__$4;// correcto caracteres permitods, y guiones bajos para la separacion o simulacion de especio

